language: python
python:
- '3.4'
- '3.5'
- '3.6'
- '3.7'
install:
- pip install networkx numpy coveralls
script:
- nosetests --with-coverage --cover-package=danker
after_success:
- coveralls
deploy:
  provider: pypi
  user: thalhamm
  password:
    secure: tbqu+5VfcK/xBRHSxRJ1EfkB9WABpat/V8hm+NMSdh95M8ceheoODTNz295vFJ9XQnOGV3m9JbU7jMUmu81CpgkV8SuqzDw97CL0GNGXF9XFBaxdsHPM6bscSpw4JL660PtEm45X3f0Zsf745oQgzXDufrU1Jx2xw6x+d38fKJjWgg0PYfZa/QQW648EAC+oWQ2DyXI4H5sOh49YBnbyDCubop0TkWz/JXv/q6K4tkzQ+FJtnLgJmD9ScZSPRbwjuwWqcqgG1CDshwESatJHExC7Di4HUQ8JC64zs6zHWmY22fs28Ens0eYvZLckOxPWckeb3BnmluAAL4nsmUsQ/oxtA2pxWnNnfmChZLXHd5j++Ddkn4Pix8bUYPM1sbkOKraQpZg4AkvCnGqICgOO0X0yND2IfAfHybDUpwB7fqVUeBPCOf8WQzIQorfU1cY8+rF9b95ZkbZtdpOkuYUu94rlesqqR78JgSyjaizmqWkJ4pbG5We298UJJ6JnB1jRTEaUk0nJIiMhKGLH840C+Q8/uPe+WjU9zMf+GGAIZiSCxzRMsk2fo8xkaZ+0zTSFuTASfJ2k+VxeCTSpoLYwYCSVTBEmGcAUHtkeqQXdjvNhiUqXkzgmwHa7lr+66vGOD2c92hHqZTGuY6C5JyAepQc5wXnPVaPS2BIe7IE3egU=
  on:
    tags: true
