language: python
python:
- '3.4'
- '3.5'
- '3.6'
- '3.7'
install:
- pip install networkx numpy coveralls
script:
- nosetests --with-coverage --cover-package=danker
after_success:
- coveralls
deploy:
  provider: pypi
  user: thalhamm
  password:
    secure: FQYPNB/quZPkdFuLfM974NOVjgSQgL7ixjMPGDtPNmOhpoLoX4hUEX7Vry/KnW7Szi59QrClkOVgXHkq2BNVG+9bUOJu9+16WteiDAauaHrqKvfcT6y3MLVLGecDws7zw8SUFsoedOuIkmSVR0dRWyi+03Ns4R35V05yKIY37kbF9S/+M+S7I39E6FHkgKOcr8BZmg2HaJON2L/R5NRugpUKh5xsmzg/M94EmHGme79LDdKVoaI0MSggzBQPq+qrVmkTnlveM9J43ztuyeclDLfihyKIOcpivPwh3d8X+JX52VIBxUVIVRFpvtzBL/B4zkB8fSXYcf5LIhc6IMhhsY+I0PybXL2tKumTSQTpxIf0cWucc24W0lA73HhyumnHDuYCFIF5ewtre23GjLf5dbBWk4Twl5ssJJZWii21dfM+fsP7a3vzOaLOHo3hgAdN2HZ94uXXysS72WI+J81W+GGtKBA94dmgfodWeAjcx2Sw3b9MHVS+UPLMOmCnlwyUVDshrrxQh1FypVR3pXazVyDq8/yqdh5Zy8c3mGFvK+p7G7Xud9+Uga5tq7Ienmq/VTK/Dbgguv+lohtz2QYQC34TlYFxsxSnBfi6hUjis6I7cQG4zkgVvHQqRx89p0ZXC3TcFQTFKF82P8UCa++kUBjucZj9TDoSfDi51HgZNhQ=
  on:
    tags: true
