language: python
python:
- '3.4'
- '3.5'
- '3.6'
- '3.7'
install:
- pip install networkx numpy coveralls
script:
- nosetests --with-coverage --cover-package=danker
after_success:
- coveralls
deploy:
  provider: pypi
  user: "thalhamm"
  password:
    secure: "jVTvfGtZKUQ4NnHFxHnUe2KbcBES4Ovljt97bZSpl72NkWcuteuIElB99PY3X02LsUA1HG+w0uo6ILHuQhlBAcyAjXfEBr8TPRhhAf1s+ZUrUUOFYJClCodYBnwnxWH8EeHIgtDMvRTbPw5Xots0fAx1cgvwTcBtjZZRDJqCLTqW0W/a+BeUMWyi9VtP2/CZ7/yP8k5/KFfWB9TedMI+YbOcbGt4/5U6QNTunBOudgknHyGKqLyDiiJprh9MnwrR8711NGtvIbsdxkUMMK0aZMXOvVMRjHlHWAzllZOv0aU49vnT/xbCFdGy+KWP5ymOxFO6dvu3o0JIbloSZ4rH2u1t1H5TJhJ9Ykc/w2mGezdHuLlSd+dcaUIiSH3tmpvhUuxO3gPUbBOz1kUVTq8/p7aNJNehLeg3D44QVsInbqQe1fScpUODHyxBRz9lieKLZa3ve8LqvPNf5lXpgAXgQX9Z83EvoWsVw2NqmYftQJT+cm1RuBFMEnfknlgus1C65Ik2IQ3rG4+g4hTdT0E079BtiMQmdXWUWNfEggAKZi4u4qh0OnQTS7frSpAJ1eDuT3/1F0+Luj05w16Prv/8IB0euUH0mqAAv9VBR+sx9o5zHK7Pucsqa7v1Cjturi12wHtXJuLRI7bu+g2vmfrFiz42xR2NSeyx9k5OmouCYSs="
  on:
    tags: true
