language: python
python:
- '3.4'
- '3.5'
- '3.6'
- '3.7'
install:
- pip install networkx numpy coveralls
script:
- nosetests --with-coverage --cover-package=danker
after_success:
- coveralls
deploy:
  provider: pypi
  user: thalhamm
  password:
    secure: IcEtoeKYcM38Gns3y74UQLEMT5Gaxp3QiQNYO3QTJ7kYD7+BDyQV8hDsVL3fFExME9PfSCF7iY1JFiuUJU6f8nJC+4u/y7/iVLR2SAKSDkLdpVAVs89chZkD+gf5ZkGC5HuWHeprZc6A3rHoLNjmk6gVANh7UeqkLjn+05mElyMykp6BiC8MCtD5DpK5QRRMvlSsuXsyJu0K1r93cO/WjcesktmvZCYv3g4UUs3N+C69hRc01FIOfutGFBGWfZld31MMucHRC7CGVKBS0JzB3P9axPfC0Y9kf2pVEi0yj0N2B448EbtnkN6tX/0I83xHCVWeTliIy+8WLvyFre7E1x96aH6d+DmLsX1KZ2lTj9c3bTt4k610WKcgAM7VpgEQuyYvYLx0/WUqqZaiwWoshgV54hMT+8iEVWrTE9MuQnno6EcxuKYqiRFuAnBmK+WkwZarmVya5YHGkNVcjDFz/GQ5uMpojLifB9nx84B53jJlyrCxh6ha5ZcWcajcV4Q9sY4v6Ilyx3RNUK+aVj/lEUR5qTaYfevjI4p3ck3wiLgPqumlmmf6ooXspKWKOt8NpxP61F0LFOt3YNnHK+FatXqSwQ0sGU4gd2VC/YHRxiqEQOCsDx58IXS/yXmdGh7hSdc8jIUG4HgejKHDn6QWEfi52W7xht2YLpD0Q+Td0xk=
  on:
    tags: true
