language: python
python:
- '3.4'
- '3.5'
- '3.6'
- '3.7'
install:
- pip install networkx numpy coveralls csvkit
script:
- nosetests --with-coverage --cover-package=danker
- ./danker.sh ch
after_success:
- coveralls
