language: python
python:
  - "3.0"
  - "3.1"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install networkx numpy coveralls
script:
  - nosetests --with-coverage --cover-package=danker
after_success:
  - coveralls
